# docker-compose
services:
  payload:
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    # Let's use docker to handle the build and server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always
    # We only set the container port. Dokploy handles it on the host side
    ports:
      - 3000
    # We must use dokploy external networkl for traefik to have access to the container
    networks:
      - dokploy-network
    # traefik handle the domain
    # There should be no domain set in the GUI
    # setsetset-payload must be unique to the app
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.setsetset-payload.rule=Host(`payload.setsetset.net`)'
      - 'traefik.http.routers.setsetset-payload.entrypoints=websecure'
      - 'traefik.http.routers.setsetset-payload.tls.certResolver=letsencrypt'
      - 'traefik.http.services.setsetset-payload.loadbalancer.server.port=3000'

  mongo:
    image: mongo:latest
    hostname: setsetset-mongo
    ports:
      - 27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: ${MONGO_LOG_DRIVER:-none}
    networks:
      - dokploy-network

volumes:
  data:
  node_modules:

networks:
  dokploy-network:
    external: true
