version: '3'

services:
  payload:
    image: node:18-alpine
    expose:
      - '${HOST_PORT:-3000}'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c 'corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm build && pnpm start'
    depends_on:
      - mongo
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.payload.rule=Host(`payload.setsetset.net`)'
      - 'traefik.http.routers.payload.entrypoints=websecure'
      - 'traefik.http.routers.payload.tls.certresolver=letsencrypt'
      - 'traefik.http.services.payload.loadbalancer.server.port=${HOST_PORT:-3000}'
    networks:
      - dokploy-network


  mongo:
    image: mongo:latest
    hostname: setsetset-mongo
    ports:
      - '${MONGO_PORT:-27017}'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: ${MONGO_LOG_DRIVER:-none}
    networks:
      - dokploy-network

volumes:
  data:
  node_modules:

networks:
  dokploy-network:
    external: true