services:
  payload:
    image: node:18-alpine
    ports:
      - '${HOST_PORT:-3000}'
      - 80
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c 'corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm build && pnpm start'
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - dokploy-network

  mongo:
    image: mongo:latest
    hostname: setsetset-mongo
    ports:
      - '${MONGO_PORT:-27017}'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: ${MONGO_LOG_DRIVER:-none}
    networks:
      - dokploy-network

volumes:
  data:
  node_modules:

networks:
  dokploy-network:
    external: true