services:
  payload:
    image: node:24-alpine
    container_name: setsetset-payload
    ports:
      - '${HOST_PORT:-3000}:${HOST_PORT:-3000}'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - setsetset-network

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    container_name: setsetset-mongo
    ports:
      - '${MONGO_PORT:-27017}:${MONGO_PORT:-27017}'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - setsetset-network

volumes:
  data:
  node_modules:

networks:
  setsetset-network:
    name: setsetset-network
